### ISSUE TITLE
How to generate the superpoint.pt?

### ISSUE THREAD

**Issue by liubamboo** [robintzeng/SuperPointPretrainCpp#1]
Hello, Thanks for your greate work.
Do you know how to generate the superpoint.pt?

**Comment by robintzeng** [comment]
@liubamboo 
I use the pretrained data from others 
https://github.com/KinglittleQ/SuperPoint_SLAM
I think you can train your own weight from the python code and use it on C++ version

**Comment by liubamboo** [comment]
@robintzeng Thanks for your quick reply. And I will try your suggestion.
